############################################################
# ^------------------------------------------------------^ #
# |                       Notes                          | #
# <------------------------------------------------------> #
############################################################

Config Version: 2.0

# Welcome to the config file, here you can adjust the general settings of the plugin.
# the lines must be in YAML format, so it doesn't accept tabs, only spaces.
# And you need to make sure you have "escaped" all apostrophes in your text: If you want to write "don't", for example, write "don''t" instead (note the doubled apostrophe).

# Select the plugin language (Config will always be in english), you can select one of following languages: "en_US", "fr_FR", "es_ES", "nl_NL", "de_DE", "zh_TW", "tr_TR" and "ru_RU").
# Shout-out to Kevin_H (https://www.spigotmc.org/members/kevin_h.1393842/) for the "zh_TW" translation, K-ReportBot (https://www.spigotmc.org/members/k-reportbot.1777793/) for the "ru_RU" and "de_DE" translation, WinTone01 (https://www.spigotmc.org/members/wintone01.1485313/) for "tr_TR" and Dami1603 for the "es_ES" translation
# If you wish to contribute to the language translations (e.g. by making a translation for another language), then please visit https://github.com/CraZyRc/WhackaMole)
Language: en_US


############################################################
# ^------------------------------------------------------^ #
# |                  The Economic Side                    | #
# <------------------------------------------------------> #
############################################################

# Does your server use an Economy plugin (and do you have Vault)?
# If so then you can make it so the minigame adds the points to your economy balance.
# If your server does not use an economy plugin but uses a scoreboard, then this is also possible.
# Please select whether you'd like to be paid by "VAULT" or a "SCOREBOARD".
# If you need a tutorial for a pure vanilla Scoreboard system, please visit: https://github.com/CraZyRc/WhackaMole/wiki/V3-Install-Setup-of-the-plugin
Economy: SCOREBOARD

# What is the Scoreboard objective name that runs as your economy?
# Leave '' if you run VAULT.
Scoreboard Objective: ''

# You can specify the name of your economy currency used in messages (max 2 entries, first one is singular and second plural).
# The name of your server currency:
Singular Currency: "Dollar"
Plural Currency: "Dollars"

# Symbol of server currency.
Currency Symbol: $

# Costs to buy cooldown reset ticket.
Ticket Price: 15


############################################################
# ^------------------------------------------------------^ #
# |                     Game Options                     | #
# <------------------------------------------------------> #
############################################################

# Here you will find the general options regarding game creation and playability.

# Force player movement lock on player reward event, meaning they cannot move upon receiving their game rewards.
Player Lock: true

# Item for the hammer (Only the Material name, ALL CAPS and without "Minecraft_"):
Hammer Item: GOLDEN_AXE

# customModelData for the hammer item (in case you run a resource pack)
# More info about customModelData: https://mcmodels.net/how-to-tutorials/resource-pack-tutorials/what-is-custommodeldata-2/
# If you don't use this feature, leave the field to "0" or 2 single quotes ('')
Hammer customModelData: ''

# Custom damage value for the hammer item (in case you run a resourcepack)
# More info about tool damage values: https://www.spigotmc.org/wiki/custom-item-models-in-1-9-and-up/ (halfway through the page where it says in capital bold letters "THE RESOURCE PACK")
# If you don't use this feature, leave the field to "0" or 2 single quotes ('')
Hammer itemDamage: ''

# The list of worlds Whackamole should interact with. If this list is empty then all worlds are enabled (This is case-sensitive).
Enabled Worlds:
#  - Test

# For sounds, please refer to the Sound enum to see the Java equivalent of the minecraft sound: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html.
# What sound should be played when a mole has been hit.
HitSound: BLOCK_NOTE_BLOCK_BIT

# What sound should be played when a mole is missed.
MissedSound: BLOCK_NOTE_BLOCK_BASS

# The list of blocks the game can spawn on (generally what the surface blocks will be of the game, the visible layer of the game).
# This has to correspond to the MC blockname (to see the blockname, press F3 + H  and hover over the item, it's the part that comes after "minecraft:")
Blocklist:
  - SMOKER
  - RESPAWN_ANCHOR
  - REINFORCED_DEEPSLATE
  - DISPENSER
  - DROPPER
  - END_PORTAL_FRAME
  - BUDDING_AMETHYST
  - VAULT

# Maximum size of a created field.
Max Playfield: 25

# To what range does the game extend horizontally and vertically?
# NOTE: Set the height to '2.0' to make it so the player doesn't exit the game by jumping.
# NOTE: If you keep the width under '1.0' the player will exit the field when the player steps off the field, to add a little margin, make sure this is higher than '1.0'.
Field Extension:
  Width: 1.4
  Height: 2.5


############################################################
# ^------------------------------------------------------^ #
# |                  Permission Nodes                    | #
# <------------------------------------------------------> #
############################################################

# These are the permissions used for the plugin.
# This section of the config file is purely Information, this part is not to be edited.
# NOTE: Permission nodes inherit from the parent group. For example: the permission for Holo Create would be: "WAM.Settings.Holo.holoCreate"
General:
  wam.*: All the permissions

Game Mechanics:
  wam.resetticket: Allows the user to use reset tickets
  wam.play: Allows the user to play a game

Commands:
  wam.buy: Allows the user to buy reset tickets
  wam.reload: Allows the user to reload the plugin

  wam.game.*: Gives the user full access to the Game commands
  wam.game.create: Allows the user to create a game `/wam game create <gameName>`
  wam.game.remove: Allows the user to remove a game `/wam game remove <gameName>`
  wam.game.start: Allows the user to force start a game `/wam game start <gameName>`
  wam.game.stop: Allows the user to force stop a game `/wam game stop <gameName>`
  wam.game.toggle: Allows the user to toggle the name visibility of a game `/wam game toggle <gameName>`
  wam.game.top: Allows the user to see the topscores of a game `/wam game top <gameName> <type>`
  wam.game.edit: Allows the user to be able to edit the game grid and surrounding blocks `/wam game edit`

  wam.settings.*: Gives the user full access to the Settings commands (except for the Holo commands)
  wam.settings.get: Allows the user to get the settings of a game `/wam settings get <gameName> {setting}`
  wam.settings.set: Allows the user to set the settings of a game `/wam settings set <gameName> <setting> <value>`
  wam.settings.positions: Allows the user to set the position for different commands `/wam settings positions <gameName> <highscore/teleport/streak>`

  wam.settings.holo.*: Gives the user full access to the Holo commands
  wam.settings.holo.create: Allows the user to create a hologram `/wam settings holo create <gameName> <holoID> <type> <amount of scoreboard rows>`
  wam.settings.holo.remove: Allows the user to remove a hologram `/wam settings holo remove <gameName> <holoID>`
  wam.settings.holo.select: Allows the user to select a hologram `/wam settings holo select <gameName> <holoID>`
  wam.settings.holo.toggle: Allows the user to toggle the ID visibility of all its holograms `/wam settings holo toggle <gameName>`

