############################################################
# ^------------------------------------------------------^ #
# |                       Notes                          | #
# <------------------------------------------------------> #
############################################################

Version: ${project.version}

# Welcome to the config file, here you can adjust the output lines of the plugin.
# the lines must be in YAML format, so it doesn't accept tabs, only spaces
# And you need to make sure you have "escaped" all apostrophes in your text: If you want to write "don't", for example, write "don''t" instead (note the doubled apostrophe)



############################################################
# ^------------------------------------------------------^ #
# |                  The Written code                    | #
# <------------------------------------------------------> #
############################################################

#The list of blocks the game can spawn on (generally what the surface blocks will be of the game, the visible layer of the game)
Blocklist:
  - SMOKER
  - RESPAWN_ANCHOR
  - REINFORCED_DEEPSLATE
  - DISPENCER
  - DROPPER
  - END_PORTAL_FRAME

#The list of blocks you can use for the second layer of the game
Sub-List:
  - BROWN_MUSHROOM_BLOCK
  - MUSHROOM
  - VERDANT_FROGLIGHT

# Maximum size of a created field
Max playfield: 49

# The message that displays when the player has insufficient permissions
No Permission: "&4You do not seem to have the right permissions!"

# The message to display on the Actionbar (accepts only Json)
Actionbar Message: "[{"text":""},{"text":"[","Bold":true,"color":"#000000"},{"text":"W","bold":true,"color":"#ffd700"},{"text":"h","bold":true,"color":"#ffce00"},{"text":"a","bold":true,"color":"#ffc600"},{"text":"c","bold":true,"color":"#ffbe00"},{"text":"k","bold":true,"color":"#ffb600"},{"text":"a","bold":true,"color":"#ffae00"},{"text":"M","bold":true,"color":"#ffa600"},{"text":"o","bold":true,"color":"#ff9e00"},{"text":"l","bold":true,"color":"#ff9600"},{"text":"] ","Bold":true,"color":"#000000"},{"text":"e","bold":true,"color":"#ff8e00"},{"text":"Your score is:","bold":true,"color":"#55ffff"}]"
# Name of the hammer (accepts color codes and hex colors)
Hammer Name: "&0&l[&6&lWAM&0&l] #28c00&lS#2fca00&lMASHER"

# [{"text":""},{"text":"[","Bold":true,"color":"#000000"},{"text":"WAM","Bold":true,"color":"#ffaa00"},{"text":"] ","Bold":true,"color":"#000000"},{"text":"S","bold":true,"color":"#28c000"},{"text":"M","bold":true,"color":"#2fca00"},{"text":"A","bold":true,"color":"#37d500"},{"text":"S","bold":true,"color":"#3edf00"},{"text":"H","bold":true,"color":"#46ea00"},{"text":"E","bold":true,"color":"#4df400"},{"text":"R","bold":true,"color":"#55ff00"}]



############################################################
# ^------------------------------------------------------^ #
# |                  Permission Nodes                    | #
# <------------------------------------------------------> #
############################################################

# Every permission starts with "WAM."
Every permission: "*"

Commands:
  Create: "create"
  Remove: "Remove"
  Play: "Play"
  Settings: "Settings"