blank_issues_enabled: true
contact_links:
  - name: VAULT
    about: 'Information about Vault'
    url: 'https://www.spigotmc.org/resources/vault.34315/'
  - name: Rollercraft Discord
    about: 'Ask questions in the Dev section'
    url: 'https://discord.gg/5rK5tAYQ'